### ISSUE TITLE
InvalidOperationException in Unit2->DoThis

### ISSUE THREAD

**Issue by kekekeks** [petabridge/akka-bootcamp#81]
Exception:
```
An exception of type 'System.InvalidOperationException' occurred in System.Windows.Forms.dll but was not handled in user code

Additional information: Cross-thread operation not valid: Control 'sysChart' accessed from a thread other than the thread it was created on.
```
Stack trace
```
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.Invalidate(Boolean invalidateChildren)
   at System.Windows.Forms.DataVisualization.Charting.Chart.Invalidate()
   at System.Windows.Forms.DataVisualization.Charting.Data.DataManager.Invalidate()
   at System.Windows.Forms.DataVisualization.Charting.ChartElement.System.Windows.Forms.DataVisualization.Charting.IChartElement.Invalidate()
   at System.Windows.Forms.DataVisualization.Charting.ChartElementCollection`1.Invalidate()
   at System.Windows.Forms.DataVisualization.Charting.ChartElementCollection`1.ResumeUpdates()
   at System.Windows.Forms.DataVisualization.Charting.ChartElementCollection`1.ClearItems()
   at System.Collections.ObjectModel.Collection`1.Clear()
   at ChartApp.Actors.ChartingActor.HandleInitialize(InitializeChart ic) in c:\Users\keks\Projects\akka-bootcamp\src\Unit-2\DoThis\Actors\ChartingActor.cs:line 58
   at ChartApp.Actors.ChartingActor.OnReceive(Object message) in c:\Users\keks\Projects\akka-bootcamp\src\Unit-2\DoThis\Actors\ChartingActor.cs:line 43
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

**Comment by kekekeks** [comment]
Sorry, but Visual Studio has suspended the program and shown the exception, instead of just showing empty window as described in the lesson.
